version: "3.9"
name: media-stack

services:
  ## qBittorrent ##
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.0.3
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  ## Radarr ##
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.18.4
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  ## Sonarr ##
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:4.0.12
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  ## Prowlarr ##
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.30.2
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  ## Jellyseerr ##
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:2.3.0
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  ## Jellyfin ##
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:10.10.3
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  ## Bazarr ##
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.4.2
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - bazarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:
  bazarr-config:

networks:
  media-network:
    external: true
